Traceback (most recent call last):
  File "/home/matthias/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/matthias/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/matthias/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/matthias/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/matthias/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/matthias/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/matthias/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/matthias/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
m = simplesim.Manager(directory='advection', executable='./execute.sh', filetype='nc')
content = m.table()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileExistsError[0m                           Traceback (most recent call last)
[0;32m<ipython-input-2-9246662f9b35>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mm[0m [0;34m=[0m [0msimplesim[0m[0;34m.[0m[0mManager[0m[0;34m([0m[0mdirectory[0m[0;34m=[0m[0;34m'advection'[0m[0;34m,[0m [0mexecutable[0m[0;34m=[0m[0;34m'./execute.sh'[0m[0;34m,[0m [0mfiletype[0m[0;34m=[0m[0;34m'nc'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mcontent[0m [0;34m=[0m [0mm[0m[0;34m.[0m[0mtable[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Projekte/simplesimdb/simplesimdb.py[0m in [0;36m__init__[0;34m(self, directory, filetype, executable)[0m
[1;32m    130[0m         [0mthat[0m [0;32mis[0m [0mit[0m [0mmust[0m [0mtake[0m [0ma[0m [0mthird[0m [0margument[0m [0;34m([0m[0mthe[0m [0mprevious[0m [0msimulation[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    131[0m         """
[0;32m--> 132[0;31m         [0mself[0m[0;34m.[0m[0mdirectory[0m [0;34m=[0m [0mdirectory[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    133[0m         [0mos[0m[0;34m.[0m[0mmakedirs[0m[0;34m([0m [0mself[0m[0;34m.[0m[0m__directory[0m[0;34m,[0m [0mexist_ok[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    134[0m         [0mself[0m[0;34m.[0m[0mfiletype[0m [0;34m=[0m [0mfiletype[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Projekte/simplesimdb/simplesimdb.py[0m in [0;36mdirectory[0;34m(self, directory)[0m
[1;32m    171[0m     [0;32mdef[0m [0mdirectory[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mdirectory[0m[0;34m)[0m [0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    172[0m         [0mself[0m[0;34m.[0m[0m__directory[0m [0;34m=[0m [0mdirectory[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 173[0;31m         [0mos[0m[0;34m.[0m[0mmakedirs[0m[0;34m([0m [0mself[0m[0;34m.[0m[0m__directory[0m[0;34m,[0m [0mexist_ok[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    174[0m [0;34m[0m[0m
[1;32m    175[0m     [0;34m@[0m[0mexecutable[0m[0;34m.[0m[0msetter[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/os.py[0m in [0;36mmakedirs[0;34m(name, mode, exist_ok)[0m
[1;32m    221[0m             [0;32mreturn[0m[0;34m[0m[0;34m[0m[0m
[1;32m    222[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 223[0;31m         [0mmkdir[0m[0;34m([0m[0mname[0m[0;34m,[0m [0mmode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    224[0m     [0;32mexcept[0m [0mOSError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    225[0m         [0;31m# Cannot rely on checking for EEXIST, since the operating system[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileExistsError[0m: [Errno 17] File exists: 'advection'
FileExistsError: [Errno 17] File exists: 'advection'

